# Generated by Django 4.2.2 on 2023-06-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lang1', models.CharField(max_length=50)),
                ('lang2', models.CharField(max_length=50)),
                ('frontend', models.CharField(max_length=50)),
                ('backend', models.CharField(max_length=50)),
                ('database', models.CharField(max_length=50)),
            ],
        ),
    ]
